on: push
name: PUSH TO SERVER AND RELOAD
jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: 54.39.68.61
        port: 21
        local-dir: ./build/test/
        server-dir: week_of_games/datapacks/
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
  
  rcon_test:
    needs: deploy
    runs-on: ubuntu-latest
    name: RCON Test
    steps:
      - name: RCON Connection
        uses: Plagiatus/RCON-Action@v0.1
        with:
          server: ${{ secrets.rcon_server }}
          port: ${{ secrets.rcon_port }}
          password: ${{ secrets.rcon_password }}
          commands: '["reload"]'
