name: RCON Test

on: 
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  rcon_test:
    runs-on: ubuntu-latest
    name: RCON Test
    steps:
      - name: RCON Connection
        uses: Plagiatus/RCON-Action@v0.1
        with:
          server: ${{ secrets.rcon_server }}
          port: ${{ secrets.rcon_port }}
          password: ${{ secrets.rcon_password }}
          commands: '["reload"]'
